name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24.0"

      - name: Run tests
        run: go test ./... --coverprofile=coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          files: coverage.txt
          token: "${{ secrets.CODECOV_TOKEN }}"
